[package]
name = "run"
version = "0.1.0"
edition = "2021"

[dependencies]


[profile.dev]
overflow-checks = false
strip = true

[profile.release]
overflow-checks = false
codegen-units = 1
lto = "fat"
opt-level = 3
strip = true